# Generated by Django 5.2.4 on 2026-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tipo',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('cobertura', 'Cobertura'), ('terreno', 'Área/Terreno'), ('comercial', 'Comercial'), ('condominio', 'Condomínio fechado'), ('flat', 'Flat')], max_length=20),
        ),
    ]
