# Generated by Django 5.2.4 on 2026-09-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bairro_busca',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='cidade_busca',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='logradouro_busca',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='uf',
            field=models.CharField(default='PB', max_length=2),
        ),
    ]
