# Generated by Django 5.2.4 on 2026-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_normalize_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='localizacao_exata',
            field=models.BooleanField(default=False),
        ),
    ]
