server {
  listen 80;
  server_name serveimoveisjp.com.br www.serveimoveisjp.com.br;
  return 301 https://servenegociosimobiliarios.com.br$request_uri;
}

server {
  listen 80;
  server_name servenegociosimobiliarios.com.br www.servenegociosimobiliarios.com.br;
  return 301 https://servenegociosimobiliarios.com.br$request_uri;
}

server {
  listen 443 ssl http2;
  server_name serveimoveisjp.com.br www.serveimoveisjp.com.br;

  ssl_certificate /etc/letsencrypt/live/servenegociosimobiliarios.com.br/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/servenegociosimobiliarios.com.br/privkey.pem;
  return 301 https://servenegociosimobiliarios.com.br$request_uri;
}

server {
  listen 443 ssl http2;
  server_name servenegociosimobiliarios.com.br www.servenegociosimobiliarios.com.br;

  ssl_certificate /etc/letsencrypt/live/servenegociosimobiliarios.com.br/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/servenegociosimobiliarios.com.br/privkey.pem;

  client_max_body_size 12m;

  location /api/ {
    proxy_pass http://127.0.0.1:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /media/ {
    proxy_pass http://127.0.0.1:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
