# Generated by Django 5.2.4 on 2026-09-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dados_imovel',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notificacao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notificacao_status',
            field=models.CharField(choices=[('nao_aplicavel', 'Não aplicável'), ('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='nao_aplicavel', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='notificacao_tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(choices=[('formulario', 'Formulario'), ('whatsapp', 'WhatsApp'), ('botao_contato', 'Botao de contato'), ('venda_imovel', 'Venda de imóvel')], default='formulario', max_length=30),
        ),
    ]
